### ISSUE TITLE
Result was implicitly discarded in do-block

### ISSUE THREAD

**Issue by sloosch** [hdgarrood/purescript-versions#4]
Tried to compile this module by using the latest development build.
Probably due to https://github.com/purescript/purescript/pull/2653 this module fails to compile.

The result of "match" is implicitly discarded here:
https://github.com/hdgarrood/purescript-versions/blob/master/src/Data/Version.purs#L133

**Comment by hdgarrood** [comment]
Is that an error and not a warning?

**Comment by hdgarrood** [comment]
Ah, it is. Okay, I can't guarantee that I'll look at this any time soon but I'd happily accept a PR.
